### Submit Feedback
POST http://localhost:3300/feedback/submit-feedback HTTP/1.1
Content-Type: application/json

{
  "firstname": "Dylan Doe",
  "lastname": "Georgescu",
  "feedback": "Really enjoying the journaling feature!",
  "email": "alex@gmail.com",
  "stars": 5
}

###

### Get All Feedback
GET http://localhost:3300/feedback/get-feedback HTTP/1.1

###
//get user details
GET http://localhost:3300/user/details?email=alex@gmail.com HTTP/1.1