### User Registration
POST http://localhost:3300/register
Content-Type: application/json

{
  "email": "alex175@gmail.com",
  "password": "password123"
}

###

### User Login
POST http://localhost:3300/login
Content-Type: application/json

{
  "email": "alex@gmail.com",
  "password": "password123"
}

### User Invalid Login
POST http://localhost:3300/login
Content-Type: application/json

{
  "email": "alex@gmail.com",
  "password": "password1234"
}

### User Details Request
GET http://localhost:3300/user/details?email=alex@gmail.com
Content-Type: application/json