### Create a New Journal Entry
POST http://localhost:3300/journal/new_entry
Content-Type: application/json

{
  "title": "Bad Entry",
  "content": "This is how my day went.",
  "email": "alxgrgsc@gmail.com"
}

###

### Get All Journal Entries
GET http://localhost:3300/journal/entries

###

### Get a Specific Journal Entry (Replace :id with actual ID)
GET http://localhost:3300/journal/entries/669577e840c339282672e830

###

### Update a Specific Journal Entry (Replace :id with actual ID)
PUT http://localhost:3300/journal/entries/669577e840c339282672e830
Content-Type: application/json

{
  "title": "Updated Entry",
  "content": "Draga coco, te iubesc."
}

###

### Delete a Specific Journal Entry (Replace :id with actual ID)
DELETE http://localhost:3300/journal/entries/669577e840c339282672e830

###

### Get Journal Entries by Email
GET http://localhost:3300/journal/entries?email=alexeei@gmail.com